### ISSUE TITLE
Is there any way to add options to shellcheck

### ISSUE THREAD

**Issue by christopher-d** [shellcheck-py/shellcheck-py#139]
Like other hooks where you can for example append the shellcheck command with "-o all" (to enable all checks).

**Comment by christopher-d** [comment]
I tried this:
```
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        **args: [ -o all ]**
```

But it does not "take" the args

**Comment by asottile** [comment]
your yaml is bad. you've passed the equivalent of `shellcheck '-o all' ...`

**Comment by christopher-d** [comment]
Ok, thanks! The following works as expected:
```
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [ "-o", "all" ]
```
